### ISSUE TITLE
run the Visualize SparseR-CNN of codes : report bugs

### ISSUE THREAD

**Issue by deeplearning123456** [PeizeSun/SparseR-CNN#32]
## Instructions To Reproduce the 🐛 Bug:
1.  run the Visualize SparseR-CNN of codes:
```
python demo/demo.py --config-file projects/SparseR-CNN/configs/sparsercnn.res50.100pro.3x.yaml --input cocodataset/test2017 --output cocodataset/save2017 --confidence-threshold 0.2 --opts MODEL.WEIGHTS output/model_final.pth
```
2. report bugs:
```
[12/09 09:50:47 detectron2]: Arguments: Namespace(confidence_threshold=0.2, config_file='projects/SparseR-CNN/configs/sparsercnn.res50.100pro.3x.yaml', input=['cocodataset/test2017'], opts=['MODEL.WEIGHTS', 'output/model_final.pth'], output='cocodataset/save2017', video_input=None, webcam=False)
Traceback (most recent call last):
  File "demo/demo.py", line 77, in <module>
    cfg = setup_cfg(args)
  File "demo/demo.py", line 23, in setup_cfg
    cfg.merge_from_file(args.config_file)
  File "/home/ubuntu/Desktop/lyq/SparseR-CNN/detectron2/config/config.py", line 54, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/root/anaconda3/envs/sparse-rcnn/lib/python3.6/site-packages/fvcore-0.1.2.post20201122-py3.6.egg/fvcore/common/config.py", line 124, in merge_from_other_cfg
  File "/root/anaconda3/envs/sparse-rcnn/lib/python3.6/site-packages/yacs-0.1.8-py3.6.egg/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/root/anaconda3/envs/sparse-rcnn/lib/python3.6/site-packages/yacs-0.1.8-py3.6.egg/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/root/anaconda3/envs/sparse-rcnn/lib/python3.6/site-packages/yacs-0.1.8-py3.6.egg/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.SparseRCNN'

```
3、my environment
ubutu16.04+cuda10.1+anaconda 4.5.4+python 3.4+torch 1.6.0+torchvision 1.6.0+cv2 4.4.0
gpu_nums 1

**Comment by deeplearning123456** [comment]
您好，我在运行可视化代码的时候报上述错误，请问有好的解决办法吗？求助

**Comment by PeizeSun** [comment]
Hi~
We updateI the code several days ago. I guess now it is not "projects/SparseR-CNN", it is "projects/SparseRCNN"

**Comment by deeplearning123456** [comment]
> Hi~
> We updateI the code several days ago. I guess now it is not "projects/SparseR-CNN", it is "projects/SparseRCNN"
你好，我按照你的提示运行了这个代码：
python demo/demo.py --config-file projects/SparseRCNN/configs/sparsercnn.res50.100pro.3x.yaml --input cocodataset/test2017 --output cocodataset/save2017 --confidence-threshold 0.2 --opts MODEL.WEIGHTS output/model_final.pth
但是依然报错，和上面的报的错误一样：
[12/10 19:54:18 detectron2]: Arguments: Namespace(confidence_threshold=0.2, config_file='projects/SparseRCNN/configs/sparsercnn.res50.100pro.3x.yaml', input=['cocodataset/test2017'], opts=['MODEL.WEIGHTS', 'output/model_final.pth'], output='cocodataset/save2017', video_input=None, webcam=False)
Traceback (most recent call last):
  File "demo/demo.py", line 77, in <module>
    cfg = setup_cfg(args)
  File "demo/demo.py", line 23, in setup_cfg
    cfg.merge_from_file(args.config_file)
  File "/home/ubuntu/Desktop/lyq/SparseR-CNN/detectron2/config/config.py", line 54, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/root/anaconda3/envs/sparse-rcnn/lib/python3.6/site-packages/fvcore-0.1.2.post20201122-py3.6.egg/fvcore/common/config.py", line 124, in merge_from_other_cfg
  File "/root/anaconda3/envs/sparse-rcnn/lib/python3.6/site-packages/yacs-0.1.8-py3.6.egg/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/root/anaconda3/envs/sparse-rcnn/lib/python3.6/site-packages/yacs-0.1.8-py3.6.egg/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/root/anaconda3/envs/sparse-rcnn/lib/python3.6/site-packages/yacs-0.1.8-py3.6.egg/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.SparseRCNN'

**Comment by deeplearning123456** [comment]
> Hi~
> We updateI the code several days ago. I guess now it is not "projects/SparseR-CNN", it is "projects/SparseRCNN"
你好，我按照你的提示运行了这个代码：
python demo/demo.py --config-file projects/SparseRCNN/configs/sparsercnn.res50.100pro.3x.yaml --input cocodataset/test2017 --output cocodataset/save2017 --confidence-threshold 0.2 --opts MODEL.WEIGHTS output/model_final.pth
但是依然报错，和上面的报的错误一样：
[12/10 19:54:18 detectron2]: Arguments: Namespace(confidence_threshold=0.2, config_file='projects/SparseRCNN/configs/sparsercnn.res50.100pro.3x.yaml', input=['cocodataset/test2017'], opts=['MODEL.WEIGHTS', 'output/model_final.pth'], output='cocodataset/save2017', video_input=None, webcam=False)
Traceback (most recent call last):
File "demo/demo.py", line 77, in
cfg = setup_cfg(args)
File "demo/demo.py", line 23, in setup_cfg
cfg.merge_from_file(args.config_file)
File "/home/ubuntu/Desktop/lyq/SparseR-CNN/detectron2/config/config.py", line 54, in merge_from_file
self.merge_from_other_cfg(loaded_cfg)
File "/root/anaconda3/envs/sparse-rcnn/lib/python3.6/site-packages/fvcore-0.1.2.post20201122-py3.6.egg/fvcore/common/config.py", line 124, in merge_from_other_cfg
File "/root/anaconda3/envs/sparse-rcnn/lib/python3.6/site-packages/yacs-0.1.8-py3.6.egg/yacs/config.py", line 217, in merge_from_other_cfg
_merge_a_into_b(cfg_other, self, self, [])
File "/root/anaconda3/envs/sparse-rcnn/lib/python3.6/site-packages/yacs-0.1.8-py3.6.egg/yacs/config.py", line 478, in _merge_a_into_b
_merge_a_into_b(v, b[k], root, key_list + [k])
File "/root/anaconda3/envs/sparse-rcnn/lib/python3.6/site-packages/yacs-0.1.8-py3.6.egg/yacs/config.py", line 491, in _merge_a_into_b
raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.SparseRCNN'

**Comment by deeplearning123456** [comment]
请问还有别的解决的办法吗？

**Comment by PeizeSun** [comment]
I tried to reproduce your bug but I didn't reproduce it.
I guess it maybe come from:
(1) Your code is not the same as our updated code.
(2) --input is followed by a image file, not a folder.

**Comment by deeplearning123456** [comment]
> I tried to reproduce your bug but I didn't reproduce it.
> I guess it maybe come from:
> (1) Your code is not the same as our updated code.
> (2) --input is followed by a image file, not a folder.

Thank you for your suggestions. I found the problem is that the code I downloaded is not your latest code, and now I have run through the code. Thank you for your continued response. But I have a question I want to ask you. I want to run your model with my own data. Can you provide me with suggestions in the code modification part?
