### ISSUE TITLE
Can't install the setup.py

### ISSUE THREAD

**Issue by wen0618** [PeizeSun/SparseR-CNN#37]
$: python setup.py build developTraceback (most recent call last):
  File "setup.py", line 12, in <module>
    from torch.utils.hipify import hipify_python
ModuleNotFoundError: No module named 'torch.utils.hipify'
My pytorch version is 1.5 .So what should I do?

**Comment by wen0618** [comment]
> $: python setup.py build developTraceback (most recent call last):
> File "setup.py", line 12, in
> from torch.utils.hipify import hipify_python
> ModuleNotFoundError: No module named 'torch.utils.hipify'
> My pytorch version is 1.5 .So what should I do?

I find it's caused by pytorch version.I use official command to install pytorch 1.6 but it's actually 0.4...Maybe my anaconda has some problem.Now I use a another environment to train.Sorry.
