### ISSUE TITLE
Can you add a simple tutorial about custom dataset?

### ISSUE THREAD

**Issue by wen0618** [PeizeSun/SparseR-CNN#48]
I followed the Detectron2 to register my dataset. But met the error like this:
##
[12/25 15:34:51] detectron2.engine.train_loop ERROR: Exception during training:
Traceback (most recent call last):
  File "/home/wxy/SparseR-CNN/detectron2/engine/train_loop.py", line 134, in train
    self.run_step()
  File "/home/wxy/SparseR-CNN/detectron2/engine/defaults.py", line 429, in run_step
    self._trainer.run_step()
  File "/home/wxy/SparseR-CNN/detectron2/engine/train_loop.py", line 228, in run_step
    loss_dict = self.model(data)
  File "/home/wxy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wxy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/wxy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wxy/SparseR-CNN/projects/SparseRCNN/sparsercnn/detector.py", line 143, in forward
    loss_dict = self.criterion(output, targets)
  File "/home/wxy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wxy/SparseR-CNN/projects/SparseRCNN/sparsercnn/loss.py", line 159, in forward
    losses.update(self.get_loss(loss, outputs, targets, indices, num_boxes))
  File "/home/wxy/SparseR-CNN/projects/SparseRCNN/sparsercnn/loss.py", line 135, in get_loss
    return loss_map[loss](outputs, targets, indices, num_boxes, **kwargs)
  File "/home/wxy/SparseR-CNN/projects/SparseRCNN/sparsercnn/loss.py", line 108, in loss_boxes
    src_boxes_ = src_boxes / image_size
RuntimeError: The size of tensor a (168) must match the size of tensor b (170) at non-singleton dimension 0
##

.
I want to know exactly which file and parameters should be modified in your project.I'am very interested in your paper.Please help if you are not too busy.

**Comment by iFighting** [comment]
> I followed the Detectron2 to register my dataset. But met the error like this:
> 
> [12/25 15:34:51] detectron2.engine.train_loop ERROR: Exception during training:
> Traceback (most recent call last):
> File "/home/wxy/SparseR-CNN/detectron2/engine/train_loop.py", line 134, in train
> self.run_step()
> File "/home/wxy/SparseR-CNN/detectron2/engine/defaults.py", line 429, in run_step
> self._trainer.run_step()
> File "/home/wxy/SparseR-CNN/detectron2/engine/train_loop.py", line 228, in run_step
> loss_dict = self.model(data)
> File "/home/wxy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/wxy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
> output = self.module(*inputs[0], **kwargs[0])
> File "/home/wxy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/wxy/SparseR-CNN/projects/SparseRCNN/sparsercnn/detector.py", line 143, in forward
> loss_dict = self.criterion(output, targets)
> File "/home/wxy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/home/wxy/SparseR-CNN/projects/SparseRCNN/sparsercnn/loss.py", line 159, in forward losses.update(self.get_loss(loss, outputs, targets, indices, num_boxes)) File "/home/wxy/SparseR-CNN/projects/SparseRCNN/sparsercnn/loss.py", line 135, in get_loss return loss_map[loss](outputs, targets, indices, num_boxes, **kwargs) File "/home/wxy/SparseR-CNN/projects/SparseRCNN/sparsercnn/loss.py", line 108, in loss_boxes src_boxes_ = src_boxes / image_size
> RuntimeError: The size of tensor a (168) must match the size of tensor b (170) at non-singleton dimension 0
> 
> .
> I want to know exactly which file and parameters should be modified in your project.I'am very interested in your paper.Please help if you are not too busy.

you can convert the custom dataset to coco style.
the error is that you should increase your num_proposals

**Comment by wen0618** [comment]
Thanks! It's true that some images contain close to 1000 targets. After I changed the num_proposals to 1000 it works.
