### ISSUE TITLE
after trained about  7000 iters.it has error.

### ISSUE THREAD

**Issue by henbucuoshanghai** [PeizeSun/SparseR-CNN#61]
Traceback (most recent call last):
  File "projects/SparseRCNN/train_net.py", line 141, in <module>
    args=(args,),
  File "/home/SparseR-CNN/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "projects/SparseRCNN/train_net.py", line 129, in main
    return trainer.train()
  File "/homeSparseR-CNN/detectron2/engine/defaults.py", line 419, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/SparseR-CNN/detectron2/engine/train_loop.py", line 135, in train
    self.after_step()
  File "/home/SparseR-CNN/detectron2/engine/train_loop.py", line 165, in after_step
    h.after_step()
  File "/home//SparseR-CNN/detectron2/engine/hooks.py", line 356, in after_step
    self._do_eval()
  File "/home/SparseR-CNN/detectron2/engine/hooks.py", line 331, in _do_eval
    results = self._func()
  File "/home/lSparseR-CNN/detectron2/engine/defaults.py", line 372, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/home/inference_on_dataset(model, data_loader, evaluator)
  File "/home//SparseR-CNN/detectron2/evaluation/evaluator.py", line 176, in inference_on_dataset
    results = evaluator.evaluate()
  File "/home//SparseR-CNN/detectron2/evaluation/coco_evaluation.py", line 173, in evaluate
    self._eval_predictions(predictions, img_ids=img_ids)
  File "/home/SparseR-CNN/detectron2/evaluation/coco_evaluation.py", line 240, in _eval_predictions
    if len(coco_results) > 0
  File "/homeSparseR-CNN/detectron2/evaluation/coco_evaluation.py", line 549, in _evaluate_predictions_on_coco
    coco_dt = coco_gt.loadRes(coco_results)
  File "/opt/conda/lib/python3.7/site-packages/pycocotools-2.0.2-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 327, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set

what is wrong?

**Comment by henbucuoshanghai** [comment]
the first time to evaluate the mode!
'voc_2007_test' is not registered by `register_coco_instances`. Therefore trying to convert it to COCO format ...   
this is the error?


Serializing 4231 elements to byte tensors and concatenating them all ...
[01/15 06:36:03 d2.data.common]: Serialized dataset takes 0.01 MiB
WARNING [01/15 06:36:03 d2.evaluation.coco_evaluation]: COCO Evaluator instantiated using config, this is deprecated behavior. Please pass in explicit arguments instead.
[01/15 06:36:03 d2.evaluation.coco_evaluation]: 'voc_2007_test' is not registered by `register_coco_instances`. Therefore trying to convert it to COCO format ...
WARNING [01/15 06:36:03 d2.data.datasets.coco]: Using previously cached COCO format annotations at './output/inference/voc_2007_test_coco_format.json'. You need to clear the cache file if your dataset has been modified.
[01/15 06:36:03 d2.evaluation.evaluator]: Start inference on 41 images
[01/15 06:36:03 d2.evaluation.evaluator]: Inference done 11/41. 0.0336 s / img. ETA=0:00:01
[01/15 06:36:04 d2.evaluation.evaluator]: Total inference time: 0:00:01.347139 (0.037421 s / img per device, on 1 devices)
[01/15 06:36:04 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:01 (0.033764 s / img per device, on 1 devices)
[01/15 06:36:04 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[01/15 06:36:04 d2.evaluation.coco_evaluation]: Saving results to ./output/inference/coco_instances_results.json
[01/15 06:36:04 d2.evaluation.coco_evaluation]: Evaluating predictions with unofficial COCO API...
Loading and preparing results...
ERROR [01/15 06:36:04 d2.engine.train_loop]: Exception during training:

**Comment by PeizeSun** [comment]
Hi~
I guess you are not running the experiments on COCO dataset, am I right?
Have you fixed this bug?
